sonar.projectKey=urbanbank
sonar.projectName=UrbanBank
sonar.projectVersion=1.0
sonar.sources=Backend,Frontend/src
sonar.exclusions=Frontend/node_modules/**,Frontend/dist/**,**/__pycache__/**,**/.venv/**,**/.pytest_cache/**,**/.ruff_cache/**
sonar.sourceEncoding=UTF-8
