apiVersion: v1
kind: ConfigMap
metadata:
  name: urbanbank-config
  namespace: urbanbank
  labels:
    app: urbanbank
data:
  BACKEND_URL: http://backend:8000
  DATABASE_HOST: postgres
  DATABASE_PORT: "5432"
  DATABASE_NAME: urbanbank
  METRIC_COLLECTION_INTERVAL_SECONDS: "120"
  BRANCH_AUTO_HEAL_INTERVAL_SECONDS: "60"
