apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: urbanbank
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres-pvc.yaml
  - postgres-service.yaml
  - postgres-deployment.yaml
  - postgres-exporter-service.yaml
  - postgres-exporter-deployment.yaml
  - backend-service.yaml
  - backend-deployment.yaml
  - backend-hpa.yaml
  - backend-pdb.yaml
  - frontend-service.yaml
  - frontend-deployment.yaml
  - frontend-pdb.yaml
  - postgres-pdb.yaml
  - ingress.yaml
  - prometheus-config.yaml
  - prometheus-pvc.yaml
  - prometheus-deployment.yaml
  - prometheus-service.yaml
  - grafana-pvc.yaml
  - grafana-datasource-config.yaml
  - grafana-alerting-config.yaml
  - grafana-dashboard-provider.yaml
  - grafana-dashboard-config.yaml
  - grafana-deployment.yaml
  - grafana-service.yaml
